port: 9101
spring:
#  profiles:
#    active:
  application:
    name: consul-server
  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/hanyaguanggit/consul-server.git
    config:
      server:
        bootstrap: true
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: consul-server
      config:
        enabled: true #是否启用配置中心功能
        format: yaml #设置配置值的格式
        prefix: config #设置配置所在目录
        profile-separator: ':' #设置配置的分隔符
        data-key: #cdf-public-admin #配置key的名字，由于Consul是K/V存储，配置存储在对应K的V中