package com.cdf.mall.commons;

/**
 * 枚举了一些常用API操作码
 * ygl
 */
public enum ResultAdminCode implements IErrorCode {
    /*
  成功统一200 ，网络错误500
  模块编码 系统2位 模块两位 错误类型吗
        例如 1101001 后台系统用户权限模块
* */
    SUCCESS(ErrorCode.SUCCESS, "操作成功"),
    FAILED(ErrorCode.FAILED, "未知错误"),


    ADMIN_DADA_NONE(ErrorCode.ADMIN_DADA_NONE,"查无数据"),
    CONVERT_DATA_ERROR(ErrorCode.CONVERT_DATA_ERROR,"数据转换异常"),
    INVALID_DATA(ErrorCode.INVALID_DATA,"非法数据类型"),
    //系统用户模块
    SAVE_SYS_USER_ERROR(ErrorCode.SAVE_SYS_USER_ERROR,"保存系统用户失败"),
    UPDATE_SYS_USER_ERROR(ErrorCode.UPDATE_SYS_USER_ERROR,"更新系统用户失败"),
    RESET_SYS_USER_PASS_ERROR(ErrorCode.RESET_SYS_USER_PASS_ERROR,"重置密码失败"),
    ADD_USER_ROLE_ERROR(ErrorCode.ADD_USER_ROLE_ERROR,"添加角色失败"),
    SELECT_SYS_USER_ERROR(ErrorCode.SELECT_SYS_USER_ERROR,"查询系统用户失败"),
    UPDATE_SYS_ROLE_ERROR(ErrorCode.UPDATE_SYS_ROLE_ERROR,"更新角色信息失败"),
    SELECT_SYS_ROLE_LIST_ERROR(ErrorCode.SELECT_SYS_ROLE_LIST_ERROR,"查询角色列表失败"),
    DELETE_SYS_ROLE_ERROR(ErrorCode.DELETE_SYS_ROLE_ERROR,"删除角色失败"),
    DELETE_SYS_USER_ERROR(ErrorCode.DELETE_SYS_USER_ERROR,"删除用户失败"),
    DELETE_USER_ROLE_ERROR(ErrorCode.DELETE_USER_ROLE_ERROR,"删除用户角色关系失败"),
    DELETE_ROLE_MENU_ERROR(ErrorCode.DELETE_ROLE_MENU_ERROR,"删除角色菜单关系失败"),
    ADMIN_USER_FORBIDDEN_ERROR(ErrorCode.ADMIN_USER_FORBIDDEN_ERROR,"该用户已被禁用！"),

    //网站结构模块
    SELECT_SITESTRUCTURE_ERROR(ErrorCode.SELECT_SITESTRUCTURE_ERROR,"查询网站结构失败"),
    SELECT_HOME_INDEX_ERROR(ErrorCode.SELECT_HOME_INDEX_ERROR,"查询首页信息失败"),
    SELECT_POSITION_TYPE_ERROR(ErrorCode.SELECT_POSITION_TYPE_ERROR,"查询位置类型失败"),
    SAVE_POSITION_TYPE_ERROR(ErrorCode.SAVE_POSITION_TYPE_ERROR,"保存位置类型失败"),
    DELETE_POSITION_TYPE_ERROR(ErrorCode.DELETE_POSITION_TYPE_ERROR,"删除位置类型失败"),
    SAVE_SITE_ERROR(ErrorCode.SAVE_SITE_ERROR,"保存网站结构失败"),
    UPDATE_SITE_ERROR(ErrorCode.UPDATE_SITE_ERROR,"更新网站结构失败"),
    UPDATE_SITE_STATUS_ERROR(ErrorCode.UPDATE_SITE_STATUS_ERROR,"网站结构状态更新失败"),
    UNDEFINED_POSITION_TYPE(ErrorCode.UNDEFINED_POSITION_TYPE,"此位置类型无法识别"),
    SELECT_REDIS_CATEGORY_AS_ERROR(ErrorCode.SELECT_REDIS_CATEGORY_AS_ERROR,"查询缓存分类广告失败"),
    SELECT_REDIS_SEARCH_HOT_WORDS_ERROR(ErrorCode.SELECT_REDIS_SEARCH_HOT_WORDS_ERROR,"查询二级页搜索热词失败"),
    SELECT_HOME_INDEX_PRODUCT_AD_ERROR(ErrorCode.SELECT_HOME_INDEX_PRODUCT_ADS_ERROR,"查询首页下方商品及广告失败"),
    SELECT_REDIS_BRAND_WALL_ERROR(ErrorCode.SELECT_REDIS_BRAND_WALL_ERROR,"查询redis品牌墙失败"),
    SET_SITESTRUCTURE_CACHE_ERROR(ErrorCode.SET_SITESTRUCTURE_CACHE_ERROR,"设置网站结构缓存失败"),
    SELECT_PAYMENT_ADS_ERROR(ErrorCode.SELECT_PAYMENT_ADS_ERROR,"查询缓存获取支付后广告位失败"),

    //文章模块
    SAVE_ARTICLE_ERROR(ErrorCode.SAVE_ARTICLE_ERROR,"保存文章失败"),
    SELECT_ARTICLE_ERROR(ErrorCode.SELECT_ARTICLE_ERROR,"查询文章失败"),
    UPDATE_ARTICLE_ERROR(ErrorCode.UPDATE_ARTICLE_ERROR,"更新文章状态失败"),
    DELETE_ARTICLE_ERROR(ErrorCode.DELETE_ARTICLE_ERROR,"删除文章失败"),
    SELECT_ARTICLE_NONE(ErrorCode.SELECT_ARTICLE_NONE,"无此文章信息"),
    SAVE_ARTICLE_CACHE_ERROR(ErrorCode.SAVE_ARTICLE_CACHE_ERROR,"保存文章缓存失败"),

    //文章栏目

    SAVE_CATEGORY_ERROR(ErrorCode.SAVE_CATEGORY_ERROR,"保存文章栏目失败"),
    UPDATE_CATEGORY_ERROR(ErrorCode.UPDATE_CATEGORY_ERROR,"更新文章栏目失败"),
    DELETE_CATEGORY_ERROR(ErrorCode.DELETE_CATEGORY_ERROR,"删除文章栏目失败"),
    SELECT_CATEGORY_ERROR(ErrorCode.SELECT_CATEGORY_ERROR,"查询文章栏目失败"),
    //图片验证码
    GET_VALID_CODE_ERROR(ErrorCode.GET_VALID_CODE_ERROR,"获取图片验证码失败"),

    //地区
    SELECT_REGION_ERROR(ErrorCode.SELECT_REGION_ERROR,"查询地区失败"),

    //会员模块
    SELECT_MEMBER_LEVEL_ERROR(ErrorCode.SELECT_MEMBER_LEVEL_ERROR,"查询会员等级失败"),
    SELECT_MEMBER_LIST_ERROR(ErrorCode.SELECT_MEMBER_LIST_ERROR,"查询会员列表失败"),
    ADD_MEMBER_ERROR(ErrorCode.ADD_MEMBER_ERROR,"添加会员失败"),
    UPDATE_MEMBER_ERROR(ErrorCode.UPDATE_MEMBER_ERROR,"编辑会员信息失败"),
    UPDATE_MEMBER_INFO_ERROR(ErrorCode.UPDATE_MEMBER_INFO_ERROR,"编辑会员个人信息失败"),
    UPDATE_MEMBER_PASS_ERROR(ErrorCode.UPDATE_MEMBER_PASS_ERROR,"修改会员密码失败"),
    SELECT_MEMBER_ERROR(ErrorCode.SELECT_MEMBER_ERROR,"查询会员信息失败"),


    //菜单
    SAVE_ROLE_MENU_ERROR(ErrorCode.SAVE_ROLE_MENU_ERROR,"保存角色权限失败。"),
    SAVE_MENU_ERROR(ErrorCode.SAVE_MENU_ERROR,"保存菜单失败"),
    DELETE_MENU_ERROR(ErrorCode.DELETE_MENU_ERROR,"删除菜单失败"),
    SELECT_MENU_ERROR(ErrorCode.SELECT_MENU_ERROR,"查询菜单失败"),
    UPDATE_MENU_STATUS_ERROR(ErrorCode.UPDATE_MENU_STATUS_ERROR,"更新菜单状态失败"),

    //订单
    SELECT_ORDER_LIST_ERRPR(ErrorCode.SELECT_ORDER_LIST_ERRPR,"条件查询订单失败"),
    ORDER_LOG_ERROR(ErrorCode.ORDER_LOG_ERROR,"查询订单日志失败"),
    SELECT_ORDER_DETAIL_ERROR(ErrorCode.SELECT_ORDER_DETAIL_ERROR,"查询订单详情失败"),
    UPDATE_ORDER_ERROR(ErrorCode.UPDATE_ORDER_ERROR,"更新订单状态失败"),
    USER_MEMBERI_ERROR(ErrorCode.USER_MEMBERI_ERROR,"验证码错误"),
    SELECT_ORDER_FLIGHT_ERROR(ErrorCode.SELECT_ORDER_FLIGHT_ERROR,"查询订单航班失败"),

    //商城页面管理相关
    SELECT_PAGE_LIST_ERROR(ErrorCode.SELECT_PAGE_LIST_ERROR,"查询商城页面列表失败"),
    UPDATE_PAGE_ERROR(ErrorCode.UPDATE_PAGE_ERROR,"更新商城页面失败"),
    SAVE_PAGE_ERROR(ErrorCode.SAVE_PAGE_ERROR,"保存商城页面信息失败"),
    UPDATE_PAGE_STATUS_ERROR(ErrorCode.UPDATE_PAGE_STATUS_ERROR,"更新商城页面状态失败"),


    //图片上传相关
    IMAGES_UPLOAD_ERROR(ErrorCode.IMAGES_UPLOAD_ERROR,"上传图片失败"),
    IMAGES_SIZE_OUT_OF_RANGE(ErrorCode.IMAGES_SIZE_OUT_OF_RANGE,"上传文件大小超出范围"),
    FILE_FORMAT_ERROR(ErrorCode.FILE_FORMAT_ERROR,"文件格式有误"),
    ZIP_UPLOAD_ERROR(ErrorCode.ZIP_UPLOAD_ERROR,"压缩包上传失败"),
    UPLOAD_FILE_NONE(ErrorCode.UPLOAD_FILE_NONE,"上传文件为空"),

    //界面管理模块相关
    SAVE_SECTION_ERROR(ErrorCode.SAVE_SECTION_ERROR,"保存模块失败"),
    SELECT_SECTION_LIST_ERROR(ErrorCode.SELECT_SECTION_LIST_ERROR,"查询模块列表异常"),
    UPDATE_SECTION_ERROR(ErrorCode.UPDATE_SECTION_ERROR,"更新模块失败"),
    UPDATE_SECTION_PICTURELINK_ERROR(ErrorCode.UPDATE_SECTION_PICTURELINK_ERROR,"更新模块图片链接失败"),
    UPDATE_SECTION_TEXTLINK_ERROR(ErrorCode.UPDATE_SECTION_TEXTLINK_ERROR,"更新文字链接失败"),
    UPDATE_SECTION_RICHTEXT_ERROR(ErrorCode.UPDATE_SECTION_RICHTEXT_ERROR,"更新富文本信息失败"),
    UPDATE_SECTION_BEST_SELLER_ERROR(ErrorCode.UPDATE_SECTION_BEST_SELLER_ERROR,"更新畅销榜单失败"),
    UPDATE_SECTION_RECOMMEND_PRODUCT_ERROR(ErrorCode.UPDATE_SECTION_RECOMMEND_PRODUCT_ERROR,"更新推荐商品失败"),
    UPDATE_SECTION_RECOMMEND_BRAND_ERROR(ErrorCode.UPDATE_SECTION_RECOMMEND_BRAND_ERROR,"更新推荐品牌失败"),
    UPDATE_SECTION_HOTWORDS_ERROR(ErrorCode.UPDATE_SECTION_HOTWORDS_ERROR,"更新搜索热词失败"),
    ADD_SECTION_RECOMMEND_BRAND_ERROR(ErrorCode.ADD_SECTION_RECOMMEND_BRAND_ERROR,"添加推荐商品失败"),
    ADD_SECTION_BEST_SELLER_ERROR(ErrorCode.ADD_SECTION_BEST_SELLER_ERROR,"添加畅销榜单失败"),
    ADD_SECTION_PICTURELINK_ERROR(ErrorCode.ADD_SECTION_PICTURELINK_ERROR,"添加图片链接失败"),
    ADD_SECTION_TEXTLINK_ERROR(ErrorCode.ADD_SECTION_TEXTLINK_ERROR,"添加文字链接失败"),
    ADD_SECTION_RICHTEXT_ERROR(ErrorCode.ADD_SECTION_RICHTEXT_ERROR,"添加富文本失败"),
    ADD_SECTION_RECOMMEND_PRODUCT_ERROR(ErrorCode.ADD_SECTION_RECOMMEND_PRODUCT_ERROR,"添加推荐商品失败"),
    ADD_SECTION_HOTWORDS_ERROR(ErrorCode.ADD_SECTION_HOTWORDS_ERROR,"添加推荐品牌失败"),
    QUERY_EDIT_DATA_ERROR(ErrorCode.QUERY_EDIT_DATA_ERROR,"查询网站结构编辑数据失败"),
    ADD_SECTION_RECOMMEND_ARTICLE_ERROR(ErrorCode.ADD_SECTION_RECOMMEND_ARTICLE_ERROR,"添加推荐文章失败"),
    UPDATE_SECTION_RECOMMEND_ARTICLE_ERROR(ErrorCode.UPDATE_SECTION_RECOMMEND_ARTICLE_ERROR,"更新推荐文章失败"),
    ADD_SECTION_RECOMMEND_CATEGORY_ERROR(ErrorCode.ADD_SECTION_RECOMMEND_CATEGORY_ERROR,"添加推荐标准分类失败"),
    UPDATE_SECTION_RECOMMEND_CATEGORY_ERROR(ErrorCode.UPDATE_SECTION_RECOMMEND_CATEGORY_ERROR,"更新标准分类失败"),
    ADD_SECTION_SHARE_ACTIVITY_ERROR(ErrorCode.ADD_SECTION_SHARE_ACTIVITY_ERROR,"添加分享活动失败"),
    UPDATE_SECTION_SHARE_ACTIVITY_ERROR(ErrorCode.UPDATE_SECTION_SHARE_ACTIVITY_ERROR,"更新分享活动失败"),
    ADD_SECTION_INDEX_FLOOR_ERROR(ErrorCode.ADD_SECTION_INDEX_FLOOR_ERROR,"添加首页楼层失败"),
    UPDATE_SECTION_INDEX_FLOOR_ERROR(ErrorCode.UPDATE_SECTION_INDEX_FLOOR_ERROR,"更新首页楼层失败"),
    SECURITYERROR(ErrorCode.SECURITYERRORAdmin, "网络请求超时，请稍后重试"),
    ADD_SECTION_CONTENT_ERROR(ErrorCode.ADD_SECTION_CONTENT_ERROR,"查询模块列表，内容添加失败"),
    ADD_SECTION_APP_LINK_ERROR(ErrorCode.ADD_SECTION_APP_LINK_ERROR,"添加小程序链接失败"),
    UPDATE_SECTION_APP_LINK_ERROR(ErrorCode.UPDATE_SECTION_APP_LINK_ERROR,"更新小程序链接失败"),
    UPDATE_SECOND_PAGE_CACHE_ERROR(ErrorCode.UPDATE_SECOND_PAGE_CACHE_ERROR,"更新二级页缓存失败"),
    DATA_INCOMPLETE(ErrorCode.DATA_INCOMPLETE,"数据库数据不完整"),
    SELECT_NONE_SECTION_ERROR(ErrorCode.SELECT_NONE_SECTION_ERROR,"查询模块不存在"),

    //请求离岛接口返回响应code
    SELECT_NON_DATA_RESERVE_ERROR(ErrorCode.SELECT_NON_DATA_RESERVE_ERROR,"查无数据"),
    VALID_GOODS_ADMIN_ERROR(ErrorCode.VALID_GOODS_ADMIN_ERROR,"验证商品信息失败"),


    //专题相关
    ADD_THEMATIC_ERROR(ErrorCode.ADD_THEMATIC_ERROR,"添加专题页失败"),
    UPDATE_THEMATIC_ERROR(ErrorCode.UPDATE_THEMATIC_ERROR,"更新专题页失败"),
    SELECT_THEMATIC_ERROR(ErrorCode.SELECT_THEMATIC_ERROR,"查询专题失败"),
    UPDATE_THEMATIC_CACHE_ERROR(ErrorCode.UPDATE_THEMATIC_CACHE_ERROR,"更新专题页缓存失败"),

    //系统参数
    SET_SYS_PARAM_CACHE_ERROR(ErrorCode.SET_SYS_PARAM_CACHE_ERROR,"设置系统参数缓存失败"),
    ;

    private long code;
    private String message;

    ResultAdminCode(long code, String message) {
        this.code = code;
        this.message = message;
    }

    public long getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
